spring.profiles.active=local
spring.application.name=SiteEntArtes
spring.datasource.url=${BD_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=user

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
JWT_SECRET=${JWT_SECRET}
HASH_SECRET=${HASH_SECRET}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-part-count=20
